import pygame, random, math
import assets
info = pygame.display.Info()
swidth = info.current_w
sheight = info.current_h


#the health bar class is built for colors, make it built for images, something like below? however below does not work :(
"""
    def init(self, x, y, w, h, maximum_hp):
            self.x = x
            self.y = y
            self.w = w
            self.h = h
            self.hp = maximum_hp
            self.maximum_hp = maximum_hp
    def draw(self, surface):
        ratio = self.hp / self.maximum_hp
        screen.blit(assets.healthbar_png, (self.x, self.y, self.w, self.h))
        screen.blit(assets.fullhealthbar_png, (self.x, self.y, self.w * ratio, self.h))
"""
class Healthbar:
    """Docstring for after"""
    def __init__(self, x, y, empty, full, maximum_hp):
        self.x, self.y = x, y
        self.full, self.empty = full, empty
        self.width, self.height = self.empty.get_width(), self.empty.get_height()
        self.current_hp, self.maximum_hp = maximum_hp, maximum_hp

    def draw(self, surface):
        """Docstring later"""
        surface.blit(self.empty, (self.x, self.y))
        ratio = self.current_hp / self.maximum_hp
        filled_space = int(self.width * ratio)
        if filled_space > 0:
            filled_image = self.full.subsurface((0, 0, filled_space, self.height))
            surface.blit(filled_image, (self.x, self.y))

class Animation:
    """
    Class that animates based on a given sheet (sprite/image) and incorporates time
    >:3 - tainted by William
    """
    def __init__(self, sheet, cooldown):
        self.frame = 0
        self.action = 0
        self.ani_list = sheet
        self.animation_cooldown = cooldown
        self.last_update = pygame.time.get_ticks()


    def update_animation(self):
        """Method that returns animation per frame, based on time."""
        current_time = pygame.time.get_ticks()

        # Checks if it is on last frame
        if current_time - self.last_update >= self.animation_cooldown:
            self.frame += 1
            self.last_update = current_time
            if self.frame >= len(self.ani_list[self.action]):
                self.frame = 0

    def final_product(self):
        """Method that returns the final animation after all frames have been processed."""
        return (self.ani_list[self.action][self.frame]) # Final frame
"""
    def change_action(self, new_action):
        self.action = new_action
"""
class Button:
    """
    Class that defines the structure of a button,
    it returns a boolean value to see if the button
    was pressed through the action variable. It does
    this through checking if the mouse was within a
    rectangle and clicked generated by given x and
    y inputs.
    """
    def __init__(self, x, y, screen, image, scale):
        """Method that initializes variables in order to use for further methods"""
        width = image.get_width()
        height = image.get_height()

        # Changes image proportions based on scale factor
        self.screen = screen
        self.image = pygame.transform.scale(image, (int(width * scale), int(height * scale)))

        # Creates a rectangle to check if a mouse is within it
        self.rect = self.image.get_rect()
        self.rect.topleft = (x, y)

        # Ensures they don't spam click
        self.clicked = False

    def draw(self):
        """Method that draws the button, and checks for user interaction"""
        action = False
        # Gets mouse position
        pos = pygame.mouse.get_pos()

        if self.rect.collidepoint(pos): # collidepoint() returns true if mouse inside rectangle
            self.image.set_alpha(128)
            if pygame.mouse.get_pressed()[0] and self.clicked == False: # Left click once
                self.clicked = True
                action = True
            if not pygame.mouse.get_pressed()[0]:
                self.clicked = False
        else:
            self.image.set_alpha(255)
        self.screen.blit(self.image, (self.rect.x, self.rect.y))

        return action # Returns if the mouse was clicked

class Bullet:
    """
    Class that handles individual bullet behavior.
    Bullets move in a specified direction and check for collision with a target.
    """
    def __init__(self, screen, weapon, image, pos, direction, scale, target = None, mini_image = None, is_mini = False, animation = False):
        self.animation = animation
        self.screen = screen

        # In case a weapon/bullet doesn't have any animation
        if self.animation == True:
         self.updateimage = image
         self.updateimage.frame = 0
         self.image = image.final_product()
        else:
         self.image = pygame.transform.scale(image, (int(image.get_width() * scale), int(image.get_height() * scale)))
        self.mini_image = mini_image
        self.rect = self.image.get_rect(center=pos)

        # The arguments for direction are based on a tuple, normalize() ensures these values can only be 0s and 1s
        self.direction = pygame.math.Vector2(direction).normalize() if direction != (0, 0) else pygame.math.Vector2(0, 0) 
        self.target = target
        self.weapon = weapon
        self.alive = True  # Bullet should still exist
        self.spawn_time = pygame.time.get_ticks()
        self.exploded, self.explode_delay = False, random.randint(500, 600)
        self.is_mini = is_mini

        # Variables defined later by methods
        self.damage, self.firerate, self.speed = self.get_attributes() # Ensures the 3 above variables are pre-defined

        if weapon == 'heartattack' and mini_image:
            self.mini_image = mini_image
            self.mini_image = pygame.transform.scale(mini_image, (int(mini_image.get_width() * (scale / 2)), int(mini_image.get_height() * (scale / 2))))
            self.spawn_time = pygame.time.get_ticks()
            self.exploded, self.explode_delay = False, random.randint(500, 600)

        elif weapon == 'diamondattack' and mini_image:
            self.mini_image = mini_image
            self.mini_image = pygame.transform.scale(mini_image, (int(mini_image.get_width() * (scale / 2)), int(mini_image.get_height() * (scale / 2))))
            self.mini_bullet_spawned = 0
            self.mini_bullet_delay = 200 # Delay in ms
            self.last_mini_bullet_spawn_time = 0
            self.max_mini_bullets = 20
        
        elif weapon == 'pinkattack':
            self.explode_delay, self.exploded = None, None


    def animatebullet(self):
        if self.animation == False:
         pass
        else:
         self.updateimage.update_animation()
         self.image = self.updateimage.final_product()

    def get_attributes(self):
        "Method that returns the attributes of a weapon"
        # Tuple classification: (damage, firerate in ms, speed of bullet)
        weapon_attributes = {
            'watergun' : (21, 100, 1000), # 36.5
            'steelsoul' : (110, None, None),
            'witherfang' : (45, None, None),
            'retributionist' : (25, None, None), # 5 shells
            'khaosclysm' : (1.5, None, None), # account for time, cap at 86
            'ashsplitter' : (155, None, None),
            'infernaltyrant' : (85, None, None),

            # Succubus
            'heartattack' : (1, 5, 1300),
            'heartattack_mini' : (1, 5, 800),
            'pinkattack' : (1, 5, 400),
            'diamondattack' : (1, 5, 300), # Reduced speed so mini-bullets have time to spawn
            'diamondattack_mini' : (1, 5, 1000),
        }

        # Checks if the input matches one of the keys in weapon_types
        if self.weapon not in weapon_attributes:
            # Raise stops the program
            raise ValueError(f"Invalid weapon type: {self.weapon}")

        self.damage, self.firerate, self.speed = weapon_attributes[self.weapon]
        return self.damage, self.firerate, self.speed

    def update(self, dt):
        """Updates bullet position and handles logic like collision and mini-bullet spawning."""
        self.rect.x += self.direction.x * self.speed * dt
        self.rect.y += self.direction.y * self.speed * dt

        # Check if off-screen (optional: you can adjust this threshold)
        if self.rect.right < 0 or self.rect.left > self.screen.get_width() or \
            self.rect.bottom < 0 or self.rect.top > self.screen.get_height():
            self.alive = False

        # Check for collision with target
        if self.target and self.rect.colliderect(self.target):
            self.alive = False
            return True  # Hit

        return False  # No hit

    def should_explode(self):
        """Method used for certain attacks that explode after a random interval."""
        if self.weapon == 'pinkattack':
            return False
        if not self.is_mini and not self.exploded and pygame.time.get_ticks() - self.spawn_time >= self.explode_delay:
            return True
        return False

    def explode(self):
        """Method that is used to blow up a bigger attack into smaller ones."""
        self.exploded = True
        mini_bullets = []
        if self.weapon == 'heartattack':
            for angle in range(0, 360, 36):  # 10 directions
                radians = math.radians(angle)
                direction = (math.cos(radians), math.sin(radians))
                self.image = assets.succubus_heart_bullet9_png
                mini_bullet = Bullet(
                    self.screen,
                    'heartattack_mini',
                    self.image,  # Can be a smaller image if desired
                    self.rect.center,
                    direction,
                    2,  # Image is already small, so scale it up
                    self.target,
                    None,
                    True
                )
                mini_bullets.append(mini_bullet)
        return mini_bullets

    def spawn_mini_diamond(self):
        """Spawns a mini-diamond if the delay has passed and the limit isn't reached."""
        current_time = pygame.time.get_ticks()
        if self.weapon == 'pinkattack':
            return None
        if self.weapon == 'diamondattack' and self.mini_bullet_spawned < self.max_mini_bullets and \
           current_time - self.last_mini_bullet_spawn_time >= self.mini_bullet_delay:
            if self.mini_image:
                mini_bullet = Bullet(
                    self.screen,
                    'diamondattack_mini',
                    self.mini_image,
                    self.rect.center,
                    (-1, 0),
                    1,
                    self.target,
                    None,
                    True
                )
                self.mini_bullet_spawned += 1
                self.last_mini_bullet_spawn_time = current_time
                return mini_bullet
        return None

    def draw(self):
        """Draws bullet on the screen."""
        self.screen.blit(self.image, self.rect)
